version: '3'

services:
  dehqonoboddb:
    container_name: dehqonoboddb
    image: postgres
    environment:
      POSTGRES_DB: db_dehqonobod
      POSTGRES_USER: dehqonoboduser
      POSTGRES_PASSWORD: dehqonobodpass
    volumes:
      - postgres_data:/var/lib/postgresql/datadehqonobod/
    ports:
      - "5432:5432"
  dehqonobodweb:
    container_name: dehqonobod
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - dehqonoboddb
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
